### ISSUE TITLE
Improve readability by avoiding `void` functions to update parameters

### ISSUE THREAD

**Issue by faisal-bhuiyan** [Exawind/openturbine#117]
https://github.com/Exawind/openturbine/blob/45aab4dbf501976640405be9250204455447dcd6/src/gebt_poc/solver.cpp#L172-L264

If you can get away with not using `void` functions to update parameters it really helps with readability.  This pattern is repeated all throughout the code. It is hard to know what is getting updated and what isn't in these types of functions.

In the instance above, I would prefer a return of the residual in this case so it is clear what the output is.  Also, in this case you are zero'ing out the residual anyways so it doesn't seem like you **need** to pass by reference. There is an argument for saving on memory allocations, but looking at the utilization of these and the memory is getting allocated right before calling it:

https://github.com/Exawind/openturbine/blob/45aab4dbf501976640405be9250204455447dcd6/src/gebt_poc/clamped_beam.cpp#L75-L78

Which I would prefer to see as:
```c++
    auto residual_gen_coords = ElementalStaticForcesResidual(
        position_vectors_, gen_coords_1D, stiffness_matrix_, quadrature_);
```

_Originally posted by @psakievich in https://github.com/Exawind/openturbine/discussions/108#discussioncomment-8401212_

**Comment by faisal-bhuiyan** [comment]
More context on this from https://github.com/Exawind/openturbine/discussions/108#discussion-6183555: There is a lot of allocations between methods that obscures the flow of the code (see my comment on void functions).

**Comment by ddement** [comment]
A note: we should also standardize on if our output variables (when necessary to avoid extra allocations) are first or last in the argument list. I think we usually use the last one, but we should ensure that we're consistent.

**Comment by faisal-bhuiyan** [comment]
Not sure if we need anything else in this regard. Should we close this, @deslaughter @ddement?
