### ISSUE TITLE
GEBT Refactor Design

### ISSUE THREAD

**Issue by deslaughter** [Exawind/openturbine#124]
Initial design of data structures for refactoring:

![Image](https://github.com/Exawind/openturbine/assets/4530253/9d31b68f-fa9f-4b04-948e-850f1590560d)

**Comment by deslaughter** [comment]
Initial concept in branch on Github
Waiting for feedback from David

**Comment by michaelasprague** [comment]
Derek has David's comments and moving forward

**Comment by michaelasprague** [comment]
In progress and going fine.   Next step getting the solver and constraints to work together with refactor.

**Comment by michaelasprague** [comment]
Main beam part is largely done -- assembly into the global iteration matrix.  Now working on the solver.

**Comment by deslaughter** [comment]
Continuing to work on the solver. Would like to refactor the `Vector`, `Quaternion`, and `RotationMatrix` classes for use in the functors.

**Comment by deslaughter** [comment]
Still working on solver, implementing tests.

**Comment by faisal-bhuiyan** [comment]
Completed [here](https://github.com/Exawind/openturbine/pull/129).
