### ISSUE TITLE
Convert IEA-15MW Blade to OpenTurbine

### ISSUE THREAD

**Issue by michaelasprague** [Exawind/openturbine#131]
Mike will start on this -- will get nodal locations for a fixed-order GEBT element and gather any other date for simulation in OpenTurbine.

**Comment by michaelasprague** [comment]
@deslaughter has completed the conversion and has done a preliminary comparison with OpenFAST on speed.  Preliminary test shows about twice as slow.   The OpenFAST rotor has prescribed BCs, so it's Dirichlet-BC in OpenFAST.  

Not yet outputing data to compare against OpenFAST.

Some questions to answer next:

- Do the two codes give very similar answers when run at the same dt?
- I assume OpenFAST is compiled with optimization flags -- was OpenTurbine?
- How large of a dt can you go with the two codes and still get stable solutions?  (I'm assuming this is with the non-tight coupled openfast)
- Are the minimal number of jacobian calculations happening? 

What's next:
- @faisal-bhuiyan should switch over to @deslaughter's branch and start testing -- write outputs so we can compare against OpenFAST
-  @faisal-bhuiyan -- run the OpenFAST case
- @deslaughter -- taking a break from OpenTurbine, but will be there to assist Faisal
- Milestone Wrap Up:  @faisal-bhuiyan need to verify that OpenTurbine is working correctly with the IEA 15 MW and perform comparisons with OpenFAST;  @ddement -- run on GPU and then do CPU performance studies (get CPU runs to not be ridiculous)
- Views are all left layout and need to be right layout with how the data is handled.

**Comment by michaelasprague** [comment]
@faisal-bhuiyan  -- has built and run OpenTurbine and now looking at OpenFAST; 

@deslaughter -- looked at OpenFAST coupling -- nodal outputs are actually at the quadrature point motions.   

Case we're running is fixed rpm under gravity load

@deslaughter -- solver.cpp is compiling under CUDA; unit test shows runtime problems due to helper functions use specified view types -- works by accident on CPU builds but layout does not work on GPUs.   Will then move on to benchmarking.

**Comment by michaelasprague** [comment]
@faisal-bhuiyan -- OpenFAST results are not making sense.  
- able to run openfast and plot the tip-displacements
- verified that in the absence of gravity that openfast 
- Derek thinks there's a mistake in the way he transferred the OpenFAST model to OpenTurbine; @michaelasprague should investigate; @faisal-bhuiyan will take the lead on this.  Estimate -- should be able to complete this afternoon.
-

**Comment by michaelasprague** [comment]
@deslaughter -- confident about the orientations, but it's no longer converging.  Linear solver is failing to solve system.   Will be working on that this morning.

@faisal-bhuiyan -- single blade under tip load -- verify that the load -- this is a uniform beam not the IEA 15 MW -- and we verified before that we were getting the same answers as OpenTurbine.   This is alarming.   Will be focused on this issue.

**Comment by michaelasprague** [comment]
![Image](https://github.com/Exawind/openturbine/assets/2040708/c68ed9b6-3eb1-432d-9b1d-3abc554b8f3f)

**Comment by faisal-bhuiyan** [comment]
Completed [here](https://github.com/Exawind/openturbine/pull/129).
