### ISSUE TITLE
Rotor Simulation Milestone Completion

### ISSUE THREAD

**Issue by michaelasprague** [Exawind/openturbine#134]
Go/No-Go: Rotor structural dynamics demonstration: Demonstrate a wind turbine rotor simulation under prescribed loading and include code verification results and automated testing results. Compare simulation time against an equivalent model simulated with OpenFAST.

**Comment by michaelasprague** [comment]
15 WM rotor is running in both OpenTurbine and OpenFAST.

For Go/No-Go milestone, we need to make reasonable effort to have OT "performant" on at least CPUs, since the timing comparison between OT and OF may influence the Go/No-Go outcomes.

**Comment by michaelasprague** [comment]
@faisal-bhuiyan: Please provide 10 sec plot that shows results for OpenFAST loosely coupled and OpenTurbine at 90% of its largest stable time step for loosely coupled OpenFAST and OpenTurbine at 90% of its largest stable time step.  So there should be three results on the plot.

**Comment by faisal-bhuiyan** [comment]
Completed [here](https://github.com/Exawind/openturbine/pull/129).
