### ISSUE TITLE
Consolidate Legacy Quaternion and Vector Operations

### ISSUE THREAD

**Issue by ddement** [Exawind/openturbine#140]
Task:  Move all legacy quaternion and vector operations to restruct_poc.  These operations should operate on views and calling code should use local stack views to improve coherency with the rest of the code and consolidate efforts with existing functions already in that folder.

Why:  Improve code coherency as well as prepare for consolidating into one true OpenTurbine.  

Done Means:  restruct_poc code no longer depends on legacy classes and duplicated functionality is consolidated.

**Comment by faisal-bhuiyan** [comment]
Thanks for taking care of this, @ddement. Does this mean all source and test code are free of the legacy calls?
