### ISSUE TITLE
Add Unit Tests for Interpolation Kernels

### ISSUE THREAD

**Issue by ddement** [Exawind/openturbine#142]
Task:  Add proper unit tests for each of the kernels doing the math to interpolate variables (e.g. InterpolateQPU, InterpolateQPVelocity_Translation)

Why:  Unit testing ensures that correctness is maintained and aid in debugging in the future.  

Done means:  An extensive set of unit tests are provided and run as part of CI.  These tests should pass on all platforms, including GPUs.

**Comment by michaelasprague** [comment]
In progress, hope to be done this afternoon.
