### ISSUE TITLE
Consolidate Duplicate Kernels

### ISSUE THREAD

**Issue by ddement** [Exawind/openturbine#144]
Task:  Identify kernels that perform the same operations and make them into a single kernel that can be called from multiple places

Why:  This will decrease the amount of duplicated code that needs to be maintained.  Future enhancements to the kernels will be quicker to implement.

Done means:  All trivially duplicated kernels have been consolidated.  A reasonable attempt has been made to make similar kernels generic.  Performance has been measured to ensure no regressions.

**Comment by michaelasprague** [comment]
In progress
