### ISSUE TITLE
Create an abstract Constraints class to support different types of constraints via inheritance

### ISSUE THREAD

**Issue by faisal-bhuiyan** [Exawind/openturbine#153]
**Task**
Create an abstract interface for different types of constraints supported in OpenTurbine.

**Why**
To treat the constraints uniformly as member of the base class, rather than duplicating code to acknowledge the different types.

**Done means**
- [ ] Refactoring of the constraints classes to establish an inheritance hierarchy
- [ ] Unit tests exist for all derived classes

**Comment by deslaughter** [comment]
I gave this a bit more thought and I don't think the inheritance based approach will work well with the Kokkos parallelism. If we could define a vector of `Constraint` type, it would be a good solution, but inevitably we'll need all the data to generate `Phi` and `B` in the GPU and we won't want to copy that in at every iteration. I do think this may be a great opportunity to define a View of `Constraint` structs that we can do a `parallel_for` over. Let's get together and come up with a list of constraint types that the struct will need to implement.
