### ISSUE TITLE
Confirm DAE-3 Constraint Formulation with massless points

### ISSUE THREAD

**Issue by michaelasprague** [Exawind/openturbine#170]

**Comment by michaelasprague** [comment]
Started on Friday; not ready for running yet.

**Comment by michaelasprague** [comment]
Placeholders in place for sizing of system matrices; mass elements but will set them to zero; working on modifying the constraint formulation with hope to have something running by tomorrow.

**Comment by deslaughter** [comment]
Tested massless points with constraints on the RotatingBeam problem and Rotor test case. Both tests passed and showed no change in the solve iterations. Branch has been pushed to OpenTurbine repo and a PR needs to be created.
