### ISSUE TITLE
Confirm that CUDA/ROCM provide sparse direct solver

### ISSUE THREAD

**Issue by michaelasprague** [Exawind/openturbine#173]

**Comment by ddement** [comment]
@michaelasprague 
Direct links to the sparse direct solvers
cuSOLVER: https://docs.nvidia.com/cuda/cusolver/#cusolversp-t-csrlsvlu
rocSOLVER: https://rocm.docs.amd.com/projects/rocSOLVER/en/latest/reference/refact.html#
Intel MKL: https://www.intel.com/content/www/us/en/docs/onemkl/developer-reference-c/2024-1/sparse-solver-routines.html

**Comment by michaelasprague** [comment]
YES!  But we still need sparse direct solver option for other hardware, especially ARM/MacMX and maybe Power9.
