### ISSUE TITLE
Read in YAML-based WindIO file to define a turbine

### ISSUE THREAD

**Issue by ddement** [Exawind/openturbine#175]
Task: Create a class which takes in a .yaml file in the [WindIO format](https://github.com/IEAWindTask37/windIO) and parses it (probably using [yaml-cpp](https://github.com/jbeder/yaml-cpp)) to define a wind turbine.

Why:  OpenTurbine needs to be able to read an input file from disk to receive user input.  

Done means: A yaml-based WindIO input file can be read and parsed successfully (does not include creating any of the OpenTurbine data structures however).

**Comment by michaelasprague** [comment]
@faisal-bhuiyan -- any updates here?

**Comment by michaelasprague** [comment]
No significant process; @faisal-bhuiyan discussing idea of using python dictionary generated outside openturbine from the yaml file.

Discussing python vs yaml-cpp here ...

**Comment by faisal-bhuiyan** [comment]
Working on implementing a logic to read yaml-based windIO input file using the [yaml-cpp](https://github.com/jbeder/yaml-cpp) library and validating it (in a similar way done [here](https://github.com/WISDEM/WISDEM/blob/develop/wisdem/inputs/validation.py)) using the [yaml schema validation library](https://github.com/joanvallve/yaml-schema-cpp/).

**Comment by faisal-bhuiyan** [comment]
Added [yaml-cpp](https://github.com/jbeder/yaml-cpp) to OpenTurbine and added logic to read a yaml node from an input file. This task assumes a prerequisite, i.e. existence of OpenTurbine input data structures to contain the turbine information (not trivial) -- adding an issue for it.

**Comment by faisal-bhuiyan** [comment]
This is 70% done -- imported the Structs based off windIO schema and added method to instantiate them. Need to wrap up this work by automating the `parse` method creation via the Python script.
