### ISSUE TITLE
Use Kokkos::SparseMatrix for system assembly

### ISSUE THREAD

**Issue by ddement** [Exawind/openturbine#178]
Task: make assemble system use `Kokkos::SparseMatrix` instead of dense matrices.

Why: This is a first step to using sparse solvers throughout the code, which will accelerate OpenTurbine considerably.  For large systems, the matrix multiplication in system assembly is the dominant cost, even greater than solving the system, so even this intermediate step is expected to be beneficial.

Done means:  The upper left quadrant of the system uses sparse matrices for assembly.  This result will then be copied into the existing dense matrix for constraint assembly and solving the final system.

**Comment by faisal-bhuiyan** [comment]
> Why: This is a first step to using sparse solvers throughout the code, which will accelerate OpenTurbine considerably. For large systems, the matrix multiplication in system assembly is the dominant cost, even greater than solving the system, so even this intermediate step is expected to be beneficial.

Could you provide some metrics for it, if it can be gathered rather quickly? The reasoning makes sense to me.

**Comment by ddement** [comment]
@michaelasprague 
Current status:
This issue is addressed by PR #180.  

In summary: the large matrix operations required to assemble the spectral finite element portion of the system matrix (the top left quadrant, not the constraints) are now performed using sparse matrices.  The results of these operations are then copied into the dense total system matrix, so no changes are observed outside of this one function.  

Performance:  I have been using a 300 element rotor problem benchmarked on NVIDIA V100S GPUs.  Before optimization, the problem took 78.5s.  Now, it takes 33.4s.  Before optimization, this function took 57.5% of the runtime; in comparison, the system solve took 33.5% of the runtime.  After optimization, this function takes about 3.3% of the total runtime.  The new bottlenecks for performance are the system solve (80%) and the constraint assembly (13%, mostly a large dense matrix multiply).  

Caveats:  I have not made any attempt to optimize this code.  We recreate the sparse matrix structure at every function call and that creation procedure can be optimized.  There's also some tuning of parameter/algorithm choice for the sparse matrix math that I didn't investigate.  For now, such optimizations would be too small to properly benchmark and not worth the time/effort.  

Next Steps:  
1.  Perform a similar optimization for the AssembleConstraints function.  This is anticipated to provide another large performance boost.  
2. Make matrix assembly no longer need dense matrices.  This will decrease high water mark memory by up to 40% and possibly simplify some of the assembly procedure.  
3. Reorganize the assembly such that copying into the global dense matrix is part of the solve step.  This is some housekeeping to allow for us to use a sparse solver.  
4. Use a sparse solver, be that through a collaboration with Kokkos-Kernels, using Amesos2, or some other strategy.

**Comment by ddement** [comment]
For those interested, here's a current benchmark of the problem (the numbers may be slightly different from reported above due to run-to-run variance):
```
<average time> <percent of total time> <percent time in Kokkos> <percent MPI imbalance> <remainder> <kernels per second> <number of calls> <name> [type]
===================
|-> 3.35e+01 sec 96.4% 5.4% 0.0% 0.2% 5.95e+01 11 Step [region]
|   |-> 2.72e+01 sec 78.4% 1.9% 0.0% 0.0% 5.66e+00 22 Solve System [region]
|   |   |-> 2.67e+01 sec 77.1% 0.3% 0.0% 99.7% 1.65e+00 22 KokkosLapack::gesv[TPL_CUSOLVER,double] [region]
|   |   |   |-> 7.35e-02 sec 0.2% 100.0% 0.0% ------ 22 Kokkos::View::initialization [getrf workspace] via memset [for]
|   |   |-> 4.11e-01 sec 1.2% 100.0% 0.0% ------ 22 PreconditionSt [for]
|   |   |-> 3.77e-02 sec 0.1% 100.0% 0.0% ------ 22 PostconditionSt [for]
|   |-> 4.64e+00 sec 13.4% 0.8% 0.0% 0.2% 9.48e+00 22 Assemble Constraints [region]
|   |   |-> 4.22e+00 sec 12.1% 0.0% 0.0% 100.0% 0.00e+00 22 KokkosBlas::gemm[TPL_CUBLAS,double] [region]
|   |   |-> 3.81e-01 sec 1.1% 0.0% 0.0% 100.0% 0.00e+00 22 KokkosBlas::gemv[TPL_CUBLAS,double] [region]
|   |   |-> 3.50e-02 sec 0.1% 100.0% 0.0% ------ 22 UpdateIterationMatrix [for]
|   |-> 1.52e+00 sec 4.4% 80.9% 0.0% 19.1% 7.39e+02 22 Assemble System [region]
|   |   |-> 3.68e-01 sec 1.1% 100.0% 0.0% ------ 22 Kokkos::ViewFill-2D [for]
|   |   |-> 2.37e-01 sec 0.7% 100.0% 0.0% ------ 22 PopulateSparseIndices [for]
|   |   |-> 1.17e-01 sec 0.3% 99.8% 0.0% 0.2% 1.88e+02 22 Assemble Elastic Stiffness Matrix [region]
|   |   |   |-> 1.17e-01 sec 0.3% 100.0% 0.0% ------ 22 IntegrateElasticStiffnessMatrix [for]
|   |   |-> 1.03e-01 sec 0.3% 99.8% 0.0% 0.2% 2.13e+02 22 Assemble Mass Matrix [region]
|   |   |   |-> 1.03e-01 sec 0.3% 100.0% 0.0% ------ 22 IntegrateMatrix [for]
|   |   |-> 1.03e-01 sec 0.3% 99.8% 0.0% 0.2% 2.14e+02 22 Assemble Gyroscopic Inertia Matrix [region]
|   |   |   |-> 1.03e-01 sec 0.3% 100.0% 0.0% ------ 22 IntegrateMatrix [for]
|   |   |-> 1.03e-01 sec 0.3% 99.9% 0.0% 0.1% 2.14e+02 22 Assemble Inertial Stiffness Matrix [region]
|   |   |   |-> 1.02e-01 sec 0.3% 100.0% 0.0% ------ 22 IntegrateMatrix [for]
|   |   |-> 4.46e-02 sec 0.1% 100.0% 0.0% ------ 22 KokkosSparse::SpAdd:Numeric::InputNotSorted [for]
|-> 3.93e-02 sec 0.1% 100.0% 0.0% ------ 600 Kokkos::ViewFill-3D [for]

KOKKOS HOST SPACE:
===================
MAX MEMORY ALLOCATED: 12035.2 kB
ALLOCATIONS AT TIME OF HIGH WATER MARK:
  35.8% qp_Cstar_mirror
  35.8% qp_Mstar_mirror
  10.9% shape_interp_mirror
  10.9% deriv_interp_mirror
  1.5% node_x0_mirror
  1.5% node_u_mirror
  1.3% node_u_dot_mirror
  1.3% node_u_ddot_mirror
  1.0% qp_weight_mirror

KOKKOS CUDA SPACE:
===================
MAX MEMORY ALLOCATED: 14056997.1 kB
ALLOCATIONS AT TIME OF HIGH WATER MARK:
  25.9% Step/Solve System/KokkosLapack::gesv[TPL_CUSOLVER,double]/getrf workspace
  25.9% St
  21.8% K
  21.8% T
  2.1% Step/Assemble System/CopyIntoSparseMatrix/Kokkos::CudaSpace::TeamScratchMemory
  2.0% gradient_matrix
```

**Comment by michaelasprague** [comment]
Ready to go; Waiting for review; ready to push in.  @deslaughter @faisal-bhuiyan
