### ISSUE TITLE
Use Kokkos Sparse Matrix for whole system assembly

### ISSUE THREAD

**Issue by ddement** [Exawind/openturbine#184]
Task:  Use only sparse matrices for assembling the final "full" system matrix.

Why: Currently, OpenTurbine uses sparse matrices for assembling the system and constraint matrices and then copies directly into the legacy dense matrix system.  This is the next step in removing our dependency on any dense matrices.  At the end of this step, the dense system matrix St will just be an implementation detail for the dense linear solver.

Done means:  St is no longer used in system assembly.  A full system sparse matrix is constructed from the individual components.  The dense solver is still used for solving the system.

**Comment by michaelasprague** [comment]
Under review; @faisal-bhuiyan @deslaughter
