### ISSUE TITLE
Refactor CMake build scripts

### ISSUE THREAD

**Issue by ddement** [Exawind/openturbine#193]
Task:  Rewrite CMake build scripts to improve organization.

Why:  We started OpenTurbine with a CMake template that was probably too big/complicated for our needs.  Since then, we have hacked on it for our own purposes/enhancements.  This story would be an almost complete rewrite of the files to ensure the build system is maintainable and fits our current needs.  It may involve removing/simplifying currently unused functionality.  

Done means:  CMake scripts are simpler and better organized.

**Comment by michaelasprague** [comment]
PR is under review.
