### ISSUE TITLE
Convert windIO schema to C++ Structs

### ISSUE THREAD

**Issue by faisal-bhuiyan** [Exawind/openturbine#198]
We need to convert the [IEA wind turbine ontology/windIO schema](https://github.com/IEAWindTask37/windIO/blob/main/windIO/turbine/IEAontology_schema.yaml) to C++ data structures. To this end, writing a quick Python script might be efficient which converts the yaml schema -> C++ `Struct`s and makes things automatic.

This task is a precursor to reading a windIO file and parsing it to create the C++ objects in OpenTurbine.

**Comment by michaelasprague** [comment]
Discussion to help David and Mike understand this; this python is meant to help write the C++ code for the data structures.  This would only change when the WindIO structure changes.

**Comment by michaelasprague** [comment]
Python script is done; final clean up needed.

**Comment by faisal-bhuiyan** [comment]
Script completed and PR submitted for review.

**Comment by faisal-bhuiyan** [comment]
Script completed, `Struct`s created as expected, issue closed as completed.
