### ISSUE TITLE
Enable CppCheck  to produce errors during CI

### ISSUE THREAD

**Issue by ddement** [Exawind/openturbine#214]
Task: Make CppCheck warnings appear as errors in CI and fix them. 

Why: We've had the CppCheck CI lines for a while, but they don't produce errors, so we haven't been fixing the warnings. This will both fix the current warnings and ensure that we don't violate the checker rules in the future. 

Done means: CppCheck produces errors instead of warnings. All CppCheck errors are fixed or suppressed in the case that they are not desired.

**Comment by michaelasprague** [comment]
2 PRs up for review.  Will review this week (Faisal and Derek)
