### ISSUE TITLE
Refactor Model and Node classes

### ISSUE THREAD

**Issue by faisal-bhuiyan** [Exawind/openturbine#216]
We need to refactor the `Model` class to store pointers to `Node` and (potentially) `Constraint` objects -- currently, we are holding copies to such objects which makes transformations difficult to keep track of.

### Change Data Structures:

- Modify the nodes vector to hold std::shared_ptr<Node>.
- Modify the constraints vector to hold std::shared_ptr<Constraint>.
- Add a std::vector<std::shared_ptr<BeamElement>> to store beam elements.

###  Update Methods to Use Pointers:

- Refactor all methods that add nodes and constraints to return pointers instead of objects.
- Ensure proper handling and storage of these pointers in the nodes, constraints, and beam_elements vectors.

###  Node Transformations:
- Add methods to the Node class to perform transformations like rotation and translation.
- Ensure transformations are reflected in the model

### Add Beam Elements:
- Implement a method to add BeamElement objects to the model.

### Testing
- Create node, add to model, transform node, make assertion on node from model class

**Comment by faisal-bhuiyan** [comment]
This is almost close to completion -- will submit PR shortly for review.

**Comment by michaelasprague** [comment]
Under review; @faisal-bhuiyan addressing comments and should be ready for merge this afternoon.
