### ISSUE TITLE
Identify physics kernels which are not covered by unit tests and write tests for them

### ISSUE THREAD

**Issue by ddement** [Exawind/openturbine#223]
Task:  Write unit tests for all physics related kernels to ensure full test coverage of this aspect of our code.  A "physics kernel" is a function object which computes values for updating the state.  These are likely located in the system, constraints, and state folders.  This does not include the "high level" functions found in the step folder, which pass data from our data structures to the physics kernels.  

Why:  Unit tests are a good, and this code has previously been covered by regression and integration testing primarily.

Done means:  All of these kernels have at least one unit test, preferably more if necessary to cover obvious variations in functionality.

**Comment by ddement** [comment]
Note: title changed to reflect change in code structure, which moved all of the physics logic out of the solver folder

**Comment by michaelasprague** [comment]
In progress and making progress.

**Comment by michaelasprague** [comment]
In progress; writing unit tests.

**Comment by michaelasprague** [comment]
Almost done.

**Comment by michaelasprague** [comment]
One more constraint; maybe done today.
