### ISSUE TITLE
Write unit tests for the matrix structure kernels in the solver folder (which aren't covered yet)

### ISSUE THREAD

**Issue by ddement** [Exawind/openturbine#224]
Task:  Write unit tests for the matrix structure kernels in the solver folder which aren't covered yet. 

Why:  Unit tests are a good, and this code has previously been covered by regression and integration testing primarily.

Done means:  All of these kernels have at least one unit test, preferably more if necessary to cover obvious variations in functionality.

**Comment by michaelasprague** [comment]
Done with about half; aiming for day or two completion

**Comment by deslaughter** [comment]
Needs to be reviewed
