### ISSUE TITLE
Separate OpenTurbine tests into unit and regression test folders/executables

### ISSUE THREAD

**Issue by ddement** [Exawind/openturbine#232]
Task:  Move regression tests into their own folder and build separate executable(s) for them.  

Why:  
1.  Historically, we've comingled our regression tests and our unit tests, making it hard to run just one or the other.  
2. Our regression tests often have features for writing to disk, visualization, or loading shared libraries, which make it hard for our testing executable to quickly run anywhere.  
3. Much of our code test coverage is provided only by regression tests.  Separating the tests will allow us to quantify our unit test coverage and expand it intelligently.  

Done means:  
1.  The tests are properly organized into their own folders and executables.  
4. All tests run when `ctest` is called.

**Comment by faisal-bhuiyan** [comment]
@ddement Just wondering if this might be a good point to take on this issue. We have amassed quite a few regression tests with rather large number of inputs required for them, separating out the directories and executables might be helpful.

**Comment by michaelasprague** [comment]
In progress and intersecting other story on unit tests
