### ISSUE TITLE
Investigate Outer Loop SIMD

### ISSUE THREAD

**Issue by ddement** [Exawind/openturbine#249]
Task:  Implement _outer loop SIMD_ by using Kokkos SIMD types as the primary type in the beams data structure.  This will change beams Views from being, for example,

`View<double***>(num_elem, num_qp, num_components)`-> `View<simd_type***>(num_super_elem, num_qp, num_components)[vec_length]` 

where, a super element is a grouping of elements of size `vec_length`, which will be platform dependent.  All math operations will need to support SIMD types instead of just doubles.

Why:  Outer loop SIMD has the potential to take advantage of CPU hardware very efficiently.  Our current usage of "middle loop SIMD" achieved a decent speed up of the integration kernels (about 2x using AVX512, which is 8 doubles wide), but it is not obvious how to use this pattern in other parts of the code, and it is not expected to scale well because our number of nodes per element will likely remain relatively small.

Done means:  Outer loop SIMD has been implemented and performance is compared to the current main implementation for a variety of problem sizes and on both GPU and CPU.

**Comment by michaelasprague** [comment]
In progress; have surrogate for main matrix iteration.  Results interesting but somewhat choppy.   Found other speed up opportunity. 

Testing on Intel Cascade Lakes
