### ISSUE TITLE
Add VTK-related code to the openturbine CI

### ISSUE THREAD

**Issue by faisal-bhuiyan** [Exawind/openturbine#256]
We need to integrate VTK-related code for visualization into our CI pipeline to ensure it remains functional and doesn’t break during development.

**Comment by ddement** [comment]
This is waiting on #251 and #253, at which point the remaining uses of ElemIndices in the VTK output should be updated and the appropriate options added to CI to ensure no further breakages.  Some testing will also be added to ensure that VTK output not only builds/runs but is correct.

**Comment by michaelasprague** [comment]
PR up that will fix vtkout on main.  @faisal-bhuiyan @deslaughter please review
