### ISSUE TITLE
Create Interface for calling AeroDyn-Inflow Library

### ISSUE THREAD

**Issue by deslaughter** [Exawind/openturbine#263]
Create an interface for calling the ADI library. Needs to handle getting information from the model and transferring to the library as well as getting output from the library (loads) and applying them to the model. This will likely need a new structure to hold data in Device. Things to figure out:

- Are the loads distributed forces/moments?
- Are loads applied to quadrature points or nodes?
- Where to apply the loads as part of the solve
- Are the loads updated in the convergence loop?

**Comment by michaelasprague** [comment]
Dev Meeting:  Should be done by end of week.  

Looking at Derek's questions:

- Are the loads distributed forces/moments?  
Point forces are given to OpenTurbine from the ADI library.

- Are loads applied to quadrature points or nodes?  
Loads are applied at Nodes. Whereas they are provided at quadrature points in OpenFAST which will cause discrepancies. 

We could ask for point forces whereever. 

User should be able to define where motion is provided from OpenTurbine along blade;
Point Forces/Moments can be provided anywhere along blade
Distributed forces/moments must be provided at all quadrature points

This is likely for further thought/discussion, but at the moment AeroDyn is going to provide point forces/loads possibly at every quadrature point, but we could use a sparser set. 

- Where to apply the loads as part of the solve?  

We need outer loop capability after this milestone.

One thing to think of is using "extrapolation" for better guess in AeroDyn

- Are the loads updated in the convergence loop?

No -- not within a newton solve
