### ISSUE TITLE
Expand CI Workflow to Include macOS

### ISSUE THREAD

**Issue by faisal-bhuiyan** [Exawind/openturbine#28]
We should consider expanding our existing [CI workflow](.github/workflows/ci.yaml) to include macOS as one of the target platforms. Currently, the workflow only runs on Linux (Ubuntu) environment. To improve cross-platform compatibility and provide a more comprehensive CI environment, it would be beneficial to expand the script to include macOS as well. It might involve the following steps:

- Add a new job in the CI script to target macOS.
- Configure the necessary steps and environment for macOS builds.
- Ensure CMake is able to build OpenTurbine on macOS.

In addition, we should look into [restoring the caching of Kokkos packages](https://github.com/Exawind/openturbine/pull/50#discussion_r1303227513) for CI runs.

**Comment by rafmudaf** [comment]
Is it worth explicitly supporting the macOS Accelerate math library? Accelerate has a [BLAS interface](https://developer.apple.com/documentation/accelerate/blas). If so, this would be a good place to test that.

**Comment by rafmudaf** [comment]
FWIW I'm just throwing this out there. I'm not sure whether this should be explicitly supported. The macOS users will probably mostly be developers rather than analysts at least in the near term. However, that might chance as the Apple chips get faster, more memory, and become a more unified architecture.

**Comment by faisal-bhuiyan** [comment]
> Is it worth explicitly supporting the macOS Accelerate math library? Accelerate has a [BLAS interface](https://developer.apple.com/documentation/accelerate/blas). If so, this would be a good place to test that.

Sorry, I didn't mean we need to support Apple Accelerate math library - just LAPACK is fine. I don't intend this to change any source code, however some CMake code might need to modified from what I have observed. I use a mac for development and the process for building OpenTurbine with the LAPACK dependency was different on mac than Linux. We should try to support developers working on different platforms and ensuring that via the CI pipeline seemed like a good idea to me.

**Comment by rafmudaf** [comment]
Ah ok, that makes sense and thanks for clarifying.
