### ISSUE TITLE
Precession example problem

### ISSUE THREAD

**Issue by wjhorne** [Exawind/openturbine#281]
Hi,

I will be working on Nalu-Wind linking to OpenTurbine for rigid body motion calculations. I know the API is still being explored for external use, but I wanted to see where the capability is at for simple physics problems. It also would be a good opportunity for me to see a little more of how OpenTurbine works. 

I have attached the first problem I would like to get working below. It is an ambiguous object with non-symmetric principal moments of inertia and initial angular velocities resulting in precession. It is a case I have seen other 6-DOF solvers use to show basic capability, e.g. S. Murman, M. Aftosmis, and M. Berger. 6-dof motion with a cartesian method. In 41st AIAA Aerospace Sciences Meeting, volume AIAA-2003-1246, 2003.

Could I get some help at how I would go about setting this problem up? Are there any particular examples that would be helpful to get me going? 

![Screenshot 2024-09-26 at 10 14 04 AM](https://github.com/user-attachments/assets/0803d3d5-cd7a-4225-8703-0a2f53fac6f3)

**Comment by deslaughter** [comment]
@wjhorne OpenTurbine currently only supports beam elements and I think this problem requires a point mass element, which will be required for the next milestone. I expect this capability to be added in the next few weeks so you can leave this issue open and you'll be notified when that feature is available. I think this is a test problem and maybe we'll add it as a regression test for the mass element.

**Comment by wjhorne** [comment]
@deslaughter Sounds good to me. This does require a point mass element. I'll leave this up and keep an eye out for notifications as you progress.

**Comment by michaelasprague** [comment]
@wjhorne where can I find the paper with the figure you posted above?  Doesn't seem to be from the AIAA paper referenced.

**Comment by wjhorne** [comment]
The figure is from my PhD. work. It ultimately is just a slightly modified version of the referenced paper's verification shown at the end of the 6-DOF verification section. It was originally shown in a book as an exact solution to the motion of a spinning and tumbling cylinder, the book being :  E. Howard Smart, Advanced Dynamics, vol. II. Dynamics of a Solid Body. MacMillen and Co., 1951.

From my perspective, matching the paper's angular velocity results would be the best way to go if you are looking for an exact case to compare. The key is that you get angular acceleration due to precession accurately to the exact solution.

**Comment by faisal-bhuiyan** [comment]
Completed in #311, please see the [precession test problem](https://github.com/Exawind/openturbine/blob/main/tests/regression_tests/regression/test_precession.cpp).

**Comment by faisal-bhuiyan** [comment]
Completed in #311, please see the [precession test problem](https://github.com/Exawind/openturbine/blob/main/tests/regression_tests/regression/test_precession.cpp).
