### ISSUE TITLE
Attempt Build on AMD GPUs

### ISSUE THREAD

**Issue by ddement** [Exawind/openturbine#282]
Task: Attempt to build and run unit tests on AMD GPUs (in particular, SNL's Caraway Machine).

Why:  Possible target machines, such as Frontier, use AMD GPUs.  We have programmed in a performance portable manner targeting CPUs and NVIDIA GPUs, but it is unknown if we can build on AMD hardware.  

Done:  We have attempted to build and run the unit tests.  Trivial compilation/runtime errors have been fixed, and more complex ones documented for further investigation.

**Comment by michaelasprague** [comment]
Done!  Complied and ran all tests with no changes to the code!!!
