### ISSUE TITLE
Clean up sparse matrix construction functions used in solver constrctor

### ISSUE THREAD

**Issue by ddement** [Exawind/openturbine#308]
Task:  Improve the code quality of the solver constructor code by performing the sparse matrix creation in parallel kernels on the GPU.  Also, add unit tests for the newly created functions which build our sparse matrices using the freedom map data structures.  

Why:  This step will improve unit test code coverage and hopefully improve the performance of solver construction (although this is not anticipated to be a bottleneck).

Done means:  the K, T, B, and B_t matrices are constructed on GPU.  Unit tests are written for their new constructors.  The old kernels for constructing these structures are deleted.

**Comment by michaelasprague** [comment]
No progress.
