### ISSUE TITLE
Benchmark and optimize sparse matrix assembly kernels

### ISSUE THREAD

**Issue by ddement** [Exawind/openturbine#310]
Task:  Benchmark our new sparse matrix assembly kernels on CPU and GPU for a few different problem sizes.  Perform optimization as necessary.

Why:  The current implementations of these assembly kernels are focused on correctness, but may or may not be leaving performance on the table.  This story is to figure out if they can be improved and improve them.

Done means:  Benchmarks have been performed on CPU and GPU for both a long running 3 blade problem with constraints and a 3000 blade problem with constraints.  If the new assembly stages are a significant contributor to the runtime, optimizations are applied to fix that.

**Comment by michaelasprague** [comment]
Dense lapack solver was implemented before getting back into this.

Required rebuilding TPLs in CI.

For this Issue, in progress

CPU benchmarks completed; only slowdown contribute to sparse matrix kernels.  3 sec to 7 sec 

May be due to atomics being used in assembly, which will add some slowdown

Currently building trilinos with CUDA to do more testing.

**Comment by ddement** [comment]
No slowdown was observed when running on GPU.

Optimizations for the serial run were applied, resulting in the code running about as fast as before the change was made - about 3 seconds for ContribueElementsToSparseMatrix for our large benchmarks.

summary of optimizations (in approximate order of how much speed up they gave for the serial build):
1.  Turned off atomics when running in serial mode (they aren't necessary)
2. Tell KokkosKernels to assume that the components are in sorted order rather than random order
3. Move populating col_idx out one loop, which should decrease the number of copies done there and improve memory access patterns.
