### ISSUE TITLE
Extend GeneralizedAlphaTimeIntegrator class to work with a State object consisting of a 3-D vector and a 4-D quaternion

### ISSUE THREAD

**Issue by faisal-bhuiyan** [Exawind/openturbine#33]
We need to enhance the generalized-alpha routine such that it works for a `7x1` generalized coordinates `q` that is composed of 3 displacement components (i.e., a `3x1` vector) and 4 quaternion components (i.e., a `4x1` vector). This will enable us to solve problems where quaternions are used to represent rotations of a rigid body.

**Comment by michaelasprague** [comment]
@faisal-bhuiyan -- I think we should strongly consider changing course and implement the HHT solver rather than generalized alpha at this point.  They are very similar, but there is more established work to follow HHT at this point.

**Comment by faisal-bhuiyan** [comment]
Relevant comment on this issue from @ddement

https://github.com/Exawind/openturbine/pull/32#issuecomment-1630866538

**Comment by faisal-bhuiyan** [comment]
Implemented in #44.
