### ISSUE TITLE
Enable Successful Build of OpenTurbine on GPUs

### ISSUE THREAD

**Issue by faisal-bhuiyan** [Exawind/openturbine#47]
Currently, OpenTurbine is primarily built and tested on CPU architectures. To take advantage of the computational power offered by GPUs, it is important to enable successful builds and testing of OpenTurbine on GPU architectures as well.

**Comment by alanw0** [comment]
That pull request only fixes the build, we'll need another one to make the tests run correctly.

**Comment by alanw0** [comment]
It's fine to link that pull request, but I didn't want this issue to close when that pull request merges.
