### ISSUE TITLE
Implement static residual for single beam

### ISSUE THREAD

**Issue by michaelasprague** [Exawind/openturbine#72]
We need to develop the infrastructure to calculate the residual vector for a single beam under static loading condition. The theoretical development for this work could be found in the accompanying [theory guide for openturbine](https://www.overleaf.com/project/651b43ae1e3d498ae5f773e4). The screenshot below provides an excerpt of the article.

![image](https://github.com/Exawind/openturbine/assets/59463700/c96b11da-5e31-4e16-8fe7-c0d43aaf8227)

**Comment by pscrozi** [comment]
Faisal is implementing this as a single large routine. He has a unit test in place. It is likely the routine will need to be broken into parts with additional new unit testing.

**Comment by pscrozi** [comment]
Faisal has been breaking this up into several different functions and pushed those changes. These can now be unit tested.

**Comment by michaelasprague** [comment]
Need perhaps two more days to implement/debug the static residual.   Need to get the results to match up with mathematica; satisfy unit tests.

**Comment by michaelasprague** [comment]
10/10 Sprint Mtg: Static residual is implemented but is failing unit tests.

**Comment by faisal-bhuiyan** [comment]
Add one more unit tests to make sure we get zero back when you set mathematica scale value to zeros.
