### ISSUE TITLE
refactoring static beam residual to utilize the field- and mesh-data structures

### ISSUE THREAD

**Issue by michaelasprague** [Exawind/openturbine#82]

**Comment by faisal-bhuiyan** [comment]
@ddement Wondering about the status of this issue - at this point we have all the bottom up logic in place. Once we reconcile the residual, iteration, and constraints to use the field and mesh DS, we can make a beeline to a static beam analysis.

**Comment by michaelasprague** [comment]
From side discussion: That's one of those dead issues.  As part of one of the previous POCs, I started to put together a more robust data structure than what we had.  This is supplanted by Derek's work that became the basis of our current work
